Make basepath and route prefix before operation optional
yuka1984/azure-functions-extensions-swashbuckle pull request #18
Opened 2019-10-30 16:11 UTC by LockTar

Add extra options to make the basepath in a swagger document optional.
Also add extra option to not to prepand the operations with the route prefix. 

These options are needed for if you want to expose your function app into api management.

Use them as follow:

```json
"Swashbuckle": {
  "PrepandOperationWithRoutePrefix": false,
  "FillSwaggerBasePathWithRoutePrefix": true
}
```

2019-11-18 15:55 UTC, yuka1984 requested changes
Please eliminate confrict.

2019-11-18 15:58 UTC, LockTar commented
Will do

2019-11-19 09:08 UTC, LockTar commented
Merged, conflict is gone

2019-11-19 10:48 UTC, Sacrep approved these changes

2019-11-19 10:54 UTC, IMAMBAKS approved these changes

2019-12-14 06:02 UTC, merged

2019-12-14 06:02 UTC, yuka1984 reviewed
LGTM